// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpcdemo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OutServiceClient is the client API for OutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OutServiceClient interface {
	MakeRequest(ctx context.Context, in *OutRequest, opts ...grpc.CallOption) (*OutResponse, error)
}

type outServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOutServiceClient(cc grpc.ClientConnInterface) OutServiceClient {
	return &outServiceClient{cc}
}

func (c *outServiceClient) MakeRequest(ctx context.Context, in *OutRequest, opts ...grpc.CallOption) (*OutResponse, error) {
	out := new(OutResponse)
	err := c.cc.Invoke(ctx, "/rpcdemo.OutService/makeRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutServiceServer is the server API for OutService service.
// All implementations must embed UnimplementedOutServiceServer
// for forward compatibility
type OutServiceServer interface {
	MakeRequest(context.Context, *OutRequest) (*OutResponse, error)
	mustEmbedUnimplementedOutServiceServer()
}

// UnimplementedOutServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOutServiceServer struct {
}

func (UnimplementedOutServiceServer) MakeRequest(context.Context, *OutRequest) (*OutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeRequest not implemented")
}
func (UnimplementedOutServiceServer) mustEmbedUnimplementedOutServiceServer() {}

// UnsafeOutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutServiceServer will
// result in compilation errors.
type UnsafeOutServiceServer interface {
	mustEmbedUnimplementedOutServiceServer()
}

func RegisterOutServiceServer(s grpc.ServiceRegistrar, srv OutServiceServer) {
	s.RegisterService(&OutService_ServiceDesc, srv)
}

func _OutService_MakeRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutServiceServer).MakeRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcdemo.OutService/makeRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutServiceServer).MakeRequest(ctx, req.(*OutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OutService_ServiceDesc is the grpc.ServiceDesc for OutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcdemo.OutService",
	HandlerType: (*OutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "makeRequest",
			Handler:    _OutService_MakeRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/rpcdemo/message.proto",
}
