// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: pkg/rpcdemo/message.proto

package rpcdemo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *OutRequest) Reset() {
	*x = OutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpcdemo_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutRequest) ProtoMessage() {}

func (x *OutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpcdemo_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutRequest.ProtoReflect.Descriptor instead.
func (*OutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpcdemo_message_proto_rawDescGZIP(), []int{0}
}

func (x *OutRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type OutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *OutResponse) Reset() {
	*x = OutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpcdemo_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutResponse) ProtoMessage() {}

func (x *OutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpcdemo_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutResponse.ProtoReflect.Descriptor instead.
func (*OutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpcdemo_message_proto_rawDescGZIP(), []int{1}
}

func (x *OutResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_pkg_rpcdemo_message_proto protoreflect.FileDescriptor

var file_pkg_rpcdemo_message_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x70, 0x63,
	0x64, 0x65, 0x6d, 0x6f, 0x22, 0x26, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x27, 0x0a, 0x0b,
	0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0x48, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x6d, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x13, 0x2e, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4f, 0x75, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x64, 0x65, 0x6d, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_rpcdemo_message_proto_rawDescOnce sync.Once
	file_pkg_rpcdemo_message_proto_rawDescData = file_pkg_rpcdemo_message_proto_rawDesc
)

func file_pkg_rpcdemo_message_proto_rawDescGZIP() []byte {
	file_pkg_rpcdemo_message_proto_rawDescOnce.Do(func() {
		file_pkg_rpcdemo_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_rpcdemo_message_proto_rawDescData)
	})
	return file_pkg_rpcdemo_message_proto_rawDescData
}

var file_pkg_rpcdemo_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_rpcdemo_message_proto_goTypes = []interface{}{
	(*OutRequest)(nil),  // 0: rpcdemo.OutRequest
	(*OutResponse)(nil), // 1: rpcdemo.OutResponse
}
var file_pkg_rpcdemo_message_proto_depIdxs = []int32{
	0, // 0: rpcdemo.OutService.makeRequest:input_type -> rpcdemo.OutRequest
	1, // 1: rpcdemo.OutService.makeRequest:output_type -> rpcdemo.OutResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_rpcdemo_message_proto_init() }
func file_pkg_rpcdemo_message_proto_init() {
	if File_pkg_rpcdemo_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_rpcdemo_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_rpcdemo_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_rpcdemo_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpcdemo_message_proto_goTypes,
		DependencyIndexes: file_pkg_rpcdemo_message_proto_depIdxs,
		MessageInfos:      file_pkg_rpcdemo_message_proto_msgTypes,
	}.Build()
	File_pkg_rpcdemo_message_proto = out.File
	file_pkg_rpcdemo_message_proto_rawDesc = nil
	file_pkg_rpcdemo_message_proto_goTypes = nil
	file_pkg_rpcdemo_message_proto_depIdxs = nil
}
